[project]
name = "forum"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]==0.115.8",
    "pydantic-settings==2.8.0",
    "pymysql==1.1.1",
    "sqlmodel>=0.0.24",
    "uvicorn[standard]>=0.34.0",
]
